version: '3.8'

services:
  multipleDocker:
    image: multiple_docker
    build:
      dockerfile: MultipleDocker/Dockerfile 
    environment:
    - urls=dockerservice/service
    ports:
    - "8080:80"
  dockerservice:
    image: docker_service
    build:
      dockerfile: DockerService/Dockerfile
    environment:
    - returnValue=Ans From service!

